### ISSUE TITLE
Chrome Extension

### ISSUE THREAD

**Issue by elia** [zetachang/trona-preview#1]
@zetachang you have any plan to release a chrome extension that will install the formatter when the devtools are opened? (see this for immutable.js https://github.com/mattzeunert/immutable-object-formatter-extension)

**Comment by zetachang** [comment]
Yeah, that's definitely on the road map! Thanks for posting suggestion 😂

**Comment by zetachang** [comment]
It's released!
👉  https://chrome.google.com/webstore/detail/trona-opal-ruby-object-fo/eoocockomfbfednckhhnajeeceonocgd
